### ISSUE TITLE
In Pharo 9 - Getting 'Instance of LcLibCrypto ddi not undertand #moduleName' when using JSONWebToken

### ISSUE THREAD

**Issue by psvensson** [noha/JSONWebToken#15]
I think I remember that the name of this methods changed in recent years, but also that there is a version of LcLibCrypto which is compatible with Pharo 9. 
![image](https://user-images.githubusercontent.com/39554/142760102-288fc24a-819f-47c0-b97a-bf33a06a6c06.png)

**Comment by noha** [comment]
Did you check https://github.com/noha/JSONWebToken/tree/pharo9-openssl1.1 ?

**Comment by noha** [comment]
I'm using this daily in pharo9 so if you agree this can be closed.

**Comment by psvensson** [comment]
Thank you. I did not remember to check for other branches.
