### ISSUE TITLE
Implement RS256 (RSA Signature with SHA-256)

### ISSUE THREAD

**Issue by tinchodias** [noha/JSONWebToken#4]
(In class JWARSASHA256)

Should it work with https://github.com/pharo-contributions/Cryptography as dependency?

(BTW, thanks for this project)

**Comment by tinchodias** [comment]
This is what I tried to reproduce: https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app

**Comment by tinchodias** [comment]
Don't know how to parse my pem file, so I opened https://github.com/pharo-contributions/Cryptography/issues/11

**Comment by noha** [comment]
Did you try RSAPublicKeyFileReader? It is in package ASN1-Readers

**Comment by tinchodias** [comment]
I desisted to fix this issue. 
My workaround was to have node installed in the OS and execute a js script from Pharo, that performs the HTTPS requests with the RS256 signature, and just use the result from Pharo.

So, I won't create a PR for this... should we close?

**Comment by noha** [comment]
Ah yes, thanks
